packages:
  - .

catalog:
  "@stylistic/eslint-plugin": ^5.10.0
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: 5.0.3

catalogMode: strict

enablePrePostScripts: true

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - vite-plus@1.0.0
  - "@voidzero-dev/*"

overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

shellEmulator: true
